### ISSUE TITLE
nbconvert v6.0.3 issue

### ISSUE THREAD

**Issue by alinscodes** [betatim/notebook-as-pdf#21]
I have updated nbconvert and that created issues with this package.

```
  File "c:\python3\lib\site-packages\nbconvert\nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "c:\python3\lib\site-packages\nbconvert\nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "c:\python3\lib\site-packages\nbconvert\nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "c:\python3\lib\site-packages\nbconvert\nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "c:\python3\lib\site-packages\nbconvert\exporters\exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "c:\python3\lib\site-packages\nbconvert\exporters\exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "c:\python3\lib\site-packages\notebook_as_pdf\__init__.py", line 227, in from_notebook_node
    heading_positions = self.pool.submit(
  File "c:\python3\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "c:\python3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "c:\python3\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\python3\lib\site-packages\nest_asyncio.py", line 29, in run
    loop = asyncio.get_event_loop()
  File "c:\python3\lib\asyncio\events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.
sys:1: RuntimeWarning: coroutine 'notebook_to_pdf' was never awaited
```

**Comment by ablascobraso** [comment]
I have the same issue by executing ```jupyter nbconvert --to PDFviaHTML Lorenz.ipynb``` on JupyterLab terminal

**Comment by betatim** [comment]
When I use https://mybinder.org/v2/gh/betatim/notebook-as-pdf/betatim-patch-2, then open a terminal and run `jupyter nbconvert --to PDFviaHTML example.ipynb` I can't reproduce the error.

This uses nbconvert 6.0.7 right now.

Could you provide a few details about what operating system and version of Python you are using? Maybe that will help with reproducing the problem.

**Comment by ablascobraso** [comment]
Sorry I did not specified that I am trying to use it in JupyterLab.

I was testing it in [https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/master?urlpath=lab/tree/demo](https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/master?urlpath=lab/tree/demo) to see if it can be applied in my current JupyterLab project.

Versions:
Python 3.7.8
nbconvert 6.0.7
notebook-as-pdf installed from master ```pip install https://github.com/betatim/notebook-as-pdf/archive/master.zip```

Error trace:
```jovyan@jupyter-jupyterlab-2djupyterlab-2ddemo-2dc3r8fcgw:~/demo$ jupyter nbconvert --to PDFviaHTML Lorenz.ipynb
[NbConvertApp] Converting notebook Lorenz.ipynb to PDFviaHTML
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook_as_pdf/__init__.py", line 235, in from_notebook_node
    **kwargs,
  File "/srv/conda/envs/notebook/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/srv/conda/envs/notebook/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/srv/conda/envs/notebook/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/srv/conda/envs/notebook/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook_as_pdf/__init__.py", line 180, in notebook_to_pdf
    heading_positions = await html_to_pdf(f.name, pdf_path, pyppeteer_args)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook_as_pdf/__init__.py", line 28, in html_to_pdf
    args=pyppeteer_args or [],
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pyppeteer/launcher.py", line 306, in launch
    return await Launcher(options, **kwargs).launch()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pyppeteer/launcher.py", line 167, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pyppeteer/launcher.py", line 226, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pyppeteer/launcher.py", line 152, in _close_process
    self._loop.run_until_complete(self.killChrome())
  File "/srv/conda/envs/notebook/lib/python3.7/asyncio/base_events.py", line 562, in run_until_complete
    self._check_closed()
  File "/srv/conda/envs/notebook/lib/python3.7/asyncio/base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'Launcher.killChrome' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback```

**Comment by betatim** [comment]
When I start the binder you linked to and run `jupyter nbconvert --version` I get 5.5.0. Did you manually update it to 6.x?

**Comment by betatim** [comment]
Can you reproduce your problem in this binder: https://mybinder.org/v2/gh/betatim/notebook-as-pdf/betatim-patch-2 ? If not could you prepare one in which you can? The simpler that binder is the better. For example the JupyterLab one you linked above is missing a few APT packages so even after installing `notebook-as-pdf` after launch it doesn't run. 

It is super hard to try and debug this without being able to reproduce it :(

**Comment by ablascobraso** [comment]
Yes, I manually updated nbconvert to 6.0.7.

I just execute it from JupyterLab terminal -> Ctrl + Shift + L to open the launcher, then click on Terminal.

You cd to where the Lorenz.ipnb notebook is found, in [https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/master?urlpath=lab/tree/demo ](https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/master?urlpath=lab/tree/demo) is into /demo folder.

And finally, once everything is installed I just run the command ```jupyter nbconvert --to PDFviaHTML Lorenz.ipynb```

I am insisting on using JupyterLab because in my current project we cannot use classic Jupyter notebooks. That is why the link that you sent me is not a good test for me. I want to prove notebook-as-pdf in JupyterLab.

In the screenshot that you sent me, when we try to export to PDF, JupyterLab is not able to display the HTML components, it returns instead ```<IPython.core.display.HTML object>``` That is why I want to use your package.

![image](https://user-images.githubusercontent.com/33316668/104590941-4e986900-566c-11eb-9dbc-7237a8c64638.png)

Please tell me if you are able to reproduce the error,

Thank you very much,

Alex

**Comment by betatim** [comment]
> You cd to where the Lorenz.ipnb notebook is found, in [mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/master?urlpath=lab/tree/demo](https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/master?urlpath=lab/tree/demo) is into /demo folder.
> 
> And finally, once everything is installed I just run the command `jupyter nbconvert --to PDFviaHTML Lorenz.ipynb`

My problem is that in the binder that gets started from the link you give not all dependencies of notebook-as-pdf are installed and because we aren't given `root` privileges we can't install them either. This means I don't understand how you can run the commands you are saying you run and get the error messages you get.

If I do what you describe I get an error related to dependencies of headless-chrome not being installed.

It should make no difference if you use jupyter lab or classic notebook to open the terminal into which `jupyter nbconvert ...` is typed. The capabilities of the terminal don't depend on whether lab or classic notebook is used.

**Comment by ablascobraso** [comment]
When you talk about dependencies you meant that ones?

APT packages listed in binder/apt.txt:
apt install libx11-xcb1
apt install libxtst6
apt install libxrandr2
apt install libasound2
apt install libpangocairo-1.0-0
apt install libatk1.0-0
apt install libatk-bridge2.0-0
apt install libgtk-3-0
apt install libnss3
apt install libxss1

The error that you get is that one?
[NbConvertApp] Converting notebook Lorenz.ipynb to PDFviaHTML
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook_as_pdf/__init__.py", line 235, in from_notebook_node
    **kwargs,
  File "/srv/conda/envs/notebook/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/srv/conda/envs/notebook/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/srv/conda/envs/notebook/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/srv/conda/envs/notebook/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook_as_pdf/__init__.py", line 180, in notebook_to_pdf
    heading_positions = await html_to_pdf(f.name, pdf_path, pyppeteer_args)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook_as_pdf/__init__.py", line 28, in html_to_pdf
    args=pyppeteer_args or [],
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pyppeteer/launcher.py", line 306, in launch
    return await Launcher(options, **kwargs).launch()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pyppeteer/launcher.py", line 167, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pyppeteer/launcher.py", line 226, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pyppeteer/launcher.py", line 152, in _close_process
    self._loop.run_until_complete(self.killChrome())
  File "/srv/conda/envs/notebook/lib/python3.7/asyncio/base_events.py", line 562, in run_until_complete
    self._check_closed()
  File "/srv/conda/envs/notebook/lib/python3.7/asyncio/base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
sys:1: RuntimeWarning: coroutine 'Launcher.killChrome' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback```

**Comment by alinscodes** [comment]
I believe if you get the latest packages and run the command below it will work:
jupyter nbconvert --to pdfviahtml (NOT PDFviaHTML)
