### ISSUE TITLE
' Chromium downloadable not found' after fresh install

### ISSUE THREAD

**Issue by Cube707** [betatim/notebook-as-pdf#45]
#### steps to reproduce 
I freshly installed the lib into a new vens using:

```sh
python -m pip install -U notebook-as-pdf
```

after that running an export fails when trying to download chromium

```
python -m nbconvert --to pdfviahtml Aufgabe1.ipynb
> OSError: Chromium downloadable not found at https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/1181205/chrome-win.zip: Received <?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: chromium-browser-snapshots/Win_x64/1181205/chrome-win.zip</Details></Error>.
```

#### System
OS: Windows 10 19045.4529
Python: v3.11.1
notebook-as-pdf: 0.5.0

#### full traceback

``` 
└─→ python -m nbconvert --to pdfviahtml Aufgabe1.ipynb 
[NbConvertApp] Converting notebook Aufgabe1.ipynb to pdfviahtml
D:\Downloads\temp\python\notebooks\.venv\Lib\site-packages\nbconvert\filters\highlight.py:71: UserWarning: IPython3 lexer unavailable, falling back on Python 3
  return _pygments_highlight(
[NbConvertApp] WARNING | Alternative text is missing on 5 image(s).
[INFO] Starting Chromium download.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Downloads\temp\python\notebooks\.venv\Lib\site-packages\nbconvert\__main__.py", line 5, in <module>
    main()
  File "D:\Downloads\temp\python\notebooks\.venv\Lib\site-packages\jupyter_core\application.py", line 283, in launch_instance
    super().launch_instance(argv=argv, **kwargs)
  File "D:\Downloads\temp\python\notebooks\.venv\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "D:\Downloads\temp\python\notebooks\.venv\Lib\site-packages\nbconvert\nbconvertapp.py", line 420, in start
    self.convert_notebooks()
  File "D:\Downloads\temp\python\notebooks\.venv\Lib\site-packages\nbconvert\nbconvertapp.py", line 597, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "D:\Downloads\temp\python\notebooks\.venv\Lib\site-packages\nbconvert\nbconvertapp.py", line 563, in convert_single_notebook
    output, resources = self.export_single_notebook(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads\temp\python\notebooks\.venv\Lib\site-packages\nbconvert\nbconvertapp.py", line 487, in export_single_notebook
    output, resources = self.exporter.from_filename(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads\temp\python\notebooks\.venv\Lib\site-packages\nbconvert\exporters\templateexporter.py", line 386, in from_filename
    return super().from_filename(filename, resources, **kw)  # type:ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads\temp\python\notebooks\.venv\Lib\site-packages\nbconvert\exporters\exporter.py", line 201, in from_filename
    return self.from_file(f, resources=resources, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads\temp\python\notebooks\.venv\Lib\site-packages\nbconvert\exporters\templateexporter.py", line 392, in from_file
    return super().from_file(file_stream, resources, **kw)  # type:ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads\temp\python\notebooks\.venv\Lib\site-packages\nbconvert\exporters\exporter.py", line 220, in from_file
    return self.from_notebook_node(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads\temp\python\notebooks\.venv\Lib\site-packages\notebook_as_pdf\__init__.py", line 240, in from_notebook_node
    ).result()
      ^^^^^^^^
  File "C:\ProgStuff\python\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\ProgStuff\python\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\ProgStuff\python\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgStuff\python\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\ProgStuff\python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgStuff\python\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Downloads\temp\python\notebooks\.venv\Lib\site-packages\notebook_as_pdf\__init__.py", line 187, in notebook_to_pdf
    heading_positions = await html_to_pdf(f.name, pdf_path, pyppeteer_args)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads\temp\python\notebooks\.venv\Lib\site-packages\notebook_as_pdf\__init__.py", line 25, in html_to_pdf
    browser = await launch(
              ^^^^^^^^^^^^^
  File "D:\Downloads\temp\python\notebooks\.venv\Lib\site-packages\pyppeteer\launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads\temp\python\notebooks\.venv\Lib\site-packages\pyppeteer\launcher.py", line 120, in __init__
    download_chromium()
  File "D:\Downloads\temp\python\notebooks\.venv\Lib\site-packages\pyppeteer\chromium_downloader.py", line 138, in download_chromium
    extract_zip(download_zip(get_url()), DOWNLOADS_FOLDER / REVISION)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads\temp\python\notebooks\.venv\Lib\site-packages\pyppeteer\chromium_downloader.py", line 82, in download_zip
    raise OSError(f'Chromium downloadable not found at {url}: ' f'Received {r.data.decode()}.\n')
OSError: Chromium downloadable not found at https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/1181205/chrome-win.zip: Received <?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: chromium-browser-snapshots/Win_x64/1181205/chrome-win.zip</Details></Error>.

```

**Comment by RozeQz** [comment]
same problem

**Comment by betatim** [comment]
This is probably because https://github.com/pyppeteer/pyppeteer is unmaintained. We use that to get a headless chrome. I think the way forward would be to port this package to the alternative that is linked in that repository. If one of you has the time to do that, that would be great. I'm not sure how quickly I'll get around to it.

There is also a "export to PDF" that is built in to jupyterlab now, so maybe that is an option as well for you?
